<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>DatasourceException.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">s0</a> &gt; <a href="index.source.html" class="el_package">edu.brown.cs.student.main.server.acsAPI</a> &gt; <span class="el_source">DatasourceException.java</span></div><h1>DatasourceException.java</h1><pre class="source lang-java linenums">package edu.brown.cs.student.main.server.acsAPI;

/**
 * This exception communicates that something went wrong with a requested datasource. It _wraps_ the
 * original cause as a field, which helps with debugging, but also allows the caller to handle the
 * issue uniformly if they wish, without looking inside.
 */
public class DatasourceException extends Exception {
  // The root cause of this datasource problem
  private final Throwable cause;

  public DatasourceException(String message) {
<span class="nc" id="L13">    super(message); // Exception message</span>
<span class="nc" id="L14">    this.cause = null;</span>
<span class="nc" id="L15">  }</span>

  public DatasourceException(String message, Throwable cause) {
<span class="nc" id="L18">    super(message); // Exception message</span>
<span class="nc" id="L19">    this.cause = cause;</span>
<span class="nc" id="L20">  }</span>

  /**
   * Returns the Throwable provided (if any) as the root cause of this exception. We don't make a
   * defensive copy here because we don't anticipate mutation of the Throwable to be any issue, and
   * because this is mostly implemented for debugging support.
   *
   * @return the root cause Throwable
   */
  public Throwable getCause() {
<span class="nc" id="L30">    return this.cause;</span>
  }
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.8.202204050719</span></div></body></html>